#!/bin/bash

#SBATCH --job-name=pst_o
#SBATCH --mail-user=deepej00@zedat.fu-berlin.de
#SBATCH --mail-type=end
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --mem-per-cpu=450
#SBATCH --time=2-23:00:00
#SBATCH --qos=standard
#SBATCH -o %J.log
#SBATCH -e %J.err

ulimit -s unlimited
export OMP_NUM_THREADS=12


export PGPLOT_DIR=/scratch/deepej00/RMCProfile_package/exe/libs
export LD_LIBRARY_PATH=/scratch/deepej00/RMCProfile_package/exe/libs
export LIBRARY_PATH=/scratch/deepej00/RMCProfile_package/exe/libs

export PATH=/scratch/deepej00/RMCProfile_package/exe:$PATH

rmcprofile PST_O_N_141414
